controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_accueil:
    path: '/accueil'
    controller: 'App\Controller\AnnivController::accueil'

app_ajouter_anniv:
    path: '/ajouter-anniv'
    controller: 'App\Controller\AnnivController::ajouterAnniv'

app_config:
    path: '/config'
    controller: 'App\Controller\AnnivController::config'

app_index:
    path: '/index'
    controller: 'App\Controller\AnnivController::index'
